Fix templates
   ERROR: ztpl.Init: template: settings_delete.gohtml:29: unterminated quoted string
   ERROR: ztpl.Init: template: settings_export.gohtml:20: bad character U+0022 '"'
   ..etc..

"string" can't contain newlines; you need to use `string` for that.

Also escape "